spring:
  application:
    name: kotlin-whisper
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024  MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8001

